name: Build and Push Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      tarsier: ${{ steps.filter.outputs.tarsier }}
      buildbase: ${{ steps.filter.outputs.tarsier }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            buildbase:
              - 'Dockerfile-base'
              - 'requirements.txt'
            tarsier:
              - 'Dockerfile'
              - 'tarsier/**/*.py'
              - 'requirements.txt'

  build-and-push:
    needs: filter-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: buildbase
            path: Dockerfile-base
            context: .
            tag: tarsier-build-base
            version: latest
            condition: ${{ needs.filter-changes.outputs.buildbase }}
          - name: tarsier
            path: Dockerfile
            context: .
            tag: tarsier
            version: 0.0.1
            condition: ${{ needs.filter-changes.outputs.tarsier }}
      fail-fast: false

    steps:
      - name: Check if component has changes
        if: ${{ matrix.component.condition != 'true' }}
        run: |
          echo "No changes detected for ${{ matrix.component.name }}. Skipping build."
          exit 0

      - name: Checkout code
        if: ${{ matrix.component.condition == 'true' }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyuncs Registry
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_TOKEN }}

      - name: Build and push ${{ matrix.component.name }} image
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.path }}
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ matrix.component.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.component.name }}
          tags: |
            registry.cn-hangzhou.aliyuncs.com/lacogito/${{ matrix.component.tag }}:${{ matrix.component.version }}
